### ISSUE TITLE
Add NotAllowedError in the code_name_map

### ISSUE THREAD

**Issue by schien** [w3c/testharness.js#218]
Presentation API will reject promise with NotAllowedError which is not listed in testharness.js, see https://github.com/w3c/web-platform-tests/blob/master/presentation-api/controlling-ua/startNewPresentation_displaynotallowed-manual.html#L32

Running that test case will hit error in https://github.com/w3c/testharness.js/blob/master/testharness.js#L1254.

**Comment by tidoust** [comment]
I already fixed that in the testharness:
https://github.com/w3c/testharness.js/commit/5ed9b8fec6ca35d1281117c4fab7fa55d25e847b

The problem is that the version of the testharness used by web-platform-tests is from two months ago and needs to be bumped. I'm not sure what is the process to do so. I'll leave this issue open in the meantime, but testharness.js should already be correct here.

**Comment by schien** [comment]
Ah, I should have searched the latest code.
Is there any issue opened for tracking the testharness update in web-platform-tests?

**Comment by tidoust** [comment]
@Ms2ger updated the version of testharness.js used in web-platform-tests a few minutes ago, @schien. The test harness no longer chokes on `NotAllowedError`.
